accounts/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
]

books_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('feeds/', include('feeds.urls')),
]

feeds/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path('today/', views.FeedTodayView.as_view(), name='today'),
    path('article/<int:article_id>', views.ArticleDetailView.as_view(), name='article'),
    path('manage-sources/', views.SourceListView.as_view(), name='manage-sources'),
]

pages/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
]

rss_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('feeds/', include(('feeds.urls', 'feeds'), namespace='feeds')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feeds/models.py
from django.db import models
from django.conf import settings

class Feed(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sources = models.ManyToManyField('Source')

    def __str__(self):
        return self.name

class Source(models.Model):
    name = models.CharField(max_length=30)
    icon = models.ImageField(upload_to='sources_icons/', blank=True)
    url = models.URLField()

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from feeds.models import Feed

class SignupView(FormView):
    template_name = 'registration/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('feeds:today')

    def post(self, request, *args, **kwargs):
        f = UserCreationForm(request.POST)
        if f.is_valid():
            new_user = f.save()
            new_feed = Feed(name='today', user=new_user)
            new_feed.save()
            return redirect('login')
        return render(request, self.template_name, {'form': f})

feeds/views.py
import requests
from lxml import etree
import os, json
from collections import OrderedDict, namedtuple
from datetime import datetime, timezone
from operator import attrgetter

from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormMixin
from django.conf import settings
from django.http import HttpResponseRedirect
from django.core.files.base import ContentFile
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Feed, Source


def try_parse_date(date_str):
    for fmt in ('%a, %d %b %Y %H:%M:%S %Z', '%a, %d %b %Y %H:%M:%S %z'):
        try:
            return datetime.strptime(date_str, fmt)
        except ValueError:
            pass
    raise ValueError('Suitable datetime format not found')


class FeedTodayView(LoginRequiredMixin, TemplateView):
    template_name='feeds/articles.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get 'today' feed of current user
        # today feed always exist for user
        today_feed = Feed.objects.get(user=self.request.user, name='today') 
        # get all sources in this feed
        context['articles_list'] = self.parse_feed_articles(today_feed)
        return context

    def parse_feed_articles(self, feed):
        # dict will have structure like this
        # { id: { 'title': '...', 'desc': '...' } }
        Article = namedtuple('Article', ['id', 'title', 'description', 'source', 'url', 'pub_date'])
        articles = []
        for source in feed.sources.all():
            # get rss data by source's link
            rss_data = requests.get(source.url).text.encode('utf-8')
            parser = etree.XMLParser(ns_clean=True, recover=True, encoding='utf-8')
            root = etree.fromstring(rss_data, parser=parser)
            titles = root.findall('.//item/title')
            descriptions = root.findall('.//item/description')
            urls = root.findall('.//item/link')
            pub_dates = root.findall('.//item/pubDate')
            for title, desc, url, pub_date in zip(titles, descriptions, urls, pub_dates):
                articles.append({
                    'id': abs(hash(title.text)),
                    'title': title.text,
                    'description': desc.text,
                    'source': source.name,
                    'url': url.text,
                    'pubDate': pub_date.text
                })
        # sort all articles by publication date
        articles.sort(key=lambda x: try_parse_date(x['pubDate']).replace(tzinfo=None))
        self.save_articles_data(articles)
        return articles


    def save_articles_data(self, articles_data):
        user_id = self.request.user.id 
        if not os.path.exists(f'{settings.MEDIA_ROOT}/{user_id}'):
            os.mkdir(f'{settings.MEDIA_ROOT}/{user_id}')
        with open(f'{settings.MEDIA_ROOT}/{user_id}/today_feed.json', 'w') as f:
            json.dump(articles_data, f, ensure_ascii=False)


class ArticleDetailView(LoginRequiredMixin, TemplateView):
    template_name='feeds/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article_id = kwargs['article_id']
        context['article'] = self.read_article_data(article_id)
        return context

    def read_article_data(self, article_id):
        user_id = self.request.user.id
        with open(f'{settings.MEDIA_ROOT}/{user_id}/today_feed.json', 'r') as f:
            articles_list = json.load(f)
            # return articles_dict[str(article_id)]
            return [art for art in articles_list if art['id'] == article_id][0] 


class SourceListView(LoginRequiredMixin, ListView):
    model = Source
    template_name = 'feeds/manage_sources.html'
    context_object_name = 'sources_list'

    # return sources for current user from 'today' feed
    def get_queryset(self):
        qs = super().get_queryset()
        today_feed = Feed.objects.get(user=self.request.user, name='today') 
        return today_feed.sources.all()

    def get(self, request, *args, **kwargs):
        print('get request')
        return super().get(request, args, kwargs)

    def post(self, request, *args, **kwargs):
        source_url = self.request.POST['source_url']

        # get source name and icon url from rss data
        rss_data = requests.get(source_url).text.encode('utf-8')
        parser = etree.XMLParser(ns_clean=True, recover=True, encoding='utf-8')
        root = etree.fromstring(rss_data, parser=parser)
        
        source_name = root.find('.//channel/title').text
        icon_url = root.find('.//channel/image/url').text
        icon_title = root.find('.//channel/image/title').text

        # save new source in 'today' feed
        new_source = Source(name=source_name, url=source_url)
        new_source.save()
        self.download_source_icon(icon_url, icon_title, new_source)
        today_feed = Feed.objects.get(user=self.request.user, name='today') 
        today_feed.sources.add(new_source)

        return HttpResponseRedirect('')

    def download_source_icon(self, icon_url, icon_title, source):
        icon_response = requests.get(icon_url)
        icon_extension = os.path.splitext(icon_url)[-1]
        icon_filename = f'{icon_title}.{icon_extension}'
        print('icon file name:', icon_filename)
        source.icon.save(icon_filename, ContentFile(icon_response.content), save=True)
        #with open(f'{settings.MEDIA_ROOT}/sources_icons/{icon_file}', 'wb') as f:
        #    f.write(icon_page.content)

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
import requests

class IndexView(TemplateView):
    template_name='pages/index.html'

    #def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
    #    f = open("../books_api_key", "r")
    #    api_key = f.read()
    #    response = requests.get(f'https://www.googleapis.com/books/v1/volumes?q=flowers+inauthor:keyes&key={api_key}') 
    #    print(response.json())


class AboutView(TemplateView):
    template_name='pages/about.html'

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
    <script src="https://kit.fontawesome.com/213607063a.js" crossorigin="anonymous"></script>

    <!-- main styles-->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <!-- <link href="https://fonts.googleapis.com/css2?family=Average+Sans&display=swap" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <header id="header" class="header">
      <div class="container-fluid">
        <div class="row align-items-start">
          <div class="col-md-6 pl-5">
              <a href="{% url 'index' %}" class="logo">
              <i class="fas fa-book"></i>
              RSSApp
              </a>
          </div>
          <div class="col-md-6 text-right pr-5">
            <a href="{% url 'login' %}" class="btn">LOGIN</a>
          </div>
        </div>
      </div>
    </header>
    <section id="main" class="main">
      {% block content %}{% endblock %}
    </section>
    <footer id="footer" class="footer">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <a href="{% url 'about' %}">About</a>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

templates/base_feed.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
    <script src="https://kit.fontawesome.com/213607063a.js" crossorigin="anonymous"></script>

    <!-- main styles-->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet">
    
    <script type="text/javascript" src="{% static 'js/article.js' %}"></script>
  </head>
  <body>
      <div class="container-fluid h-100">
          <div class="row h-100">
              <div class="col-md-2 feed_drawer">
                <p>
                  <a href="{% url 'feeds:today' %}">
                    <i class="fas fa-calendar-day"></i>
                    Today
                  </a>
                </p>
                <p>
                  <a href="{% url 'feeds:manage-sources' %}">
                    <i class="fas fa-cog"></i>
                    Sources
                  </a>
                </p>
                <p>
                  <a href="{% url 'logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                    Logout
                  </a>
                </p>
              </div>
              <div class="col-md-10">
                {% block content %}{% endblock %}
              </div>
          </div>
      </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

templates/feeds/article_detail.html
{% extends 'base_feed.html' %}
{% load static %}

{% block content %}
<h1 class="feed_section_title">{{ article.title }}</h1>
{% autoescape off %}{{ article.description }}{% endautoescape %}
<p class="lead"><a href="{{ article.url }}" target="_blank">Read more on website</a></p>
{% endblock %}

templates/feeds/articles.html
{% extends 'base_feed.html' %}

{% block content %}
    <h1 class="feed_section_title">
        Articles
    </h1>
    <table class="table table-sm articles_table">
        {% for article in articles_list %}
            <tr>
                <td>{{ article.source }}</td>
                <td><a href="{% url 'feeds:article' article_id=article.id %}">{{ article.title }}</a></td>
            </tr>    
        {% endfor %}
    </table>
{% endblock %}

templates/feeds/manage_sources.html
{% extends 'base_feed.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="feed_section_title">Manage sources</h1>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="input-group" style="margin-top: 30px;">
                    <input name="source_url" class="form-control" type="text" placeholder="Add new source">
                    <div class="input-group-append">
                        <button class="btn" type="submit">Add</button>
                    </div>
                </div>
            </form>
            <table class="table" style="margin-top: 60px;">
                <tbody>
                    {% for source in sources_list %}
                        <tr>
                            <td>{{ source }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container welcome">
        <div class="row align-items-center">
            <div class="col-md-3">
                <h1 class="welcome_title">RSS App</h1>
                <p class="welcome_msg">
                    Using django + bootstrap
                </p>
            </div>
        </div>
    </div>
{% endblock %}